export const state = () => ({
  coins: [{
      img: 'tether.svg',
      platform: 'Aave',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],

    },
    {
      img: 'tether.svg',
      platform: 'Binance',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],

    },
    {
      img: 'tether.svg',
      platform: 'Compound',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Aave',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Binance',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Compound',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Aave',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Binance',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
    {
      img: 'tether.svg',
      platform: 'Compound',
      category: ['DEX', 'DEX'],
      lockedValue: '$10.3B',
      lockedValuePercent: '+14.81%',
      allCoins: [{
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: false,
          borrowing: true,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: true,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'BTC',
          APY: '23.5%',
          stableCoin: true,
          lending: true,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },
        {
          name: 'ETH',
          APY: '23.5%',
          stableCoin: false,
          lending: true,
          borrowing: false,
          centralised: true,
          decentralised: false,
        },
        {
          name: 'KCS',
          APY: '23.5%',
          stableCoin: true,
          lending: false,
          borrowing: false,
          centralised: false,
          decentralised: true,
        },

      ],
    },
  ],
  allCentralisedCoins: [{
      img: 'tether.svg',
      coin: 'BTC'
    },
    {
      img: 'tether.svg',
      coin: 'ETH'
    },
    {
      img: 'tether.svg',
      coin: 'KCS'
    },
    {
      img: 'tether.svg',
      coin: 'BTC'
    },
    {
      img: 'tether.svg',
      coin: 'ETH'
    },
    {
      img: 'tether.svg',
      coin: 'KCS'
    }
  ],
  allDecentralisedCoins: [{
      img: 'tether.svg',
      coin: 'KCS'
    },
    {
      img: 'tether.svg',
      coin: 'ETH'
    },
    {
      img: 'tether.svg',
      coin: 'BTC'
    },
    {
      img: 'tether.svg',
      coin: 'KCS'
    },
    {
      img: 'tether.svg',
      coin: 'ETH'
    },
    {
      img: 'tether.svg',
      coin: 'BTC'
    }
  ]
})
